name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    name: Test & Audit (Node.js ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Install workspace dependencies
        run: |
          npm install --workspaces --include-workspace-root

      - name: Run all tests (unit, integration, e2e)
        run: npm test

      - name: Audit backend dependencies
        run: cd backend && npm audit --audit-level=moderate || true

      - name: Audit frontend dependencies
        run: cd ../frontend && npm audit --audit-level=moderate || true

      - name: Audit test dependencies
        run: cd ../tests && npm audit --audit-level=moderate || true

      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/test-results/
